### ISSUE TITLE
bash: ./configure: No such file or directory

### ISSUE THREAD

**Issue by babam86** [ikn/curlftpfs-ng#1]
`./configure`
```bash: ./configure: No such file or directory```

Thanks.

**Comment by ikn** [comment]
(Sorry for the late reply...)

The readme instructions are intended to be followed from a [release archive](http://ikn.org.uk/tool/curlftpfs-ng/).  I'll look at adding something to the README so it's clearer for those who read it on GitHub or get the latest from GitHub.

To build from the source repository, you must first run `autoreconf --install` to generate the `configure` script.

**Comment by sebma** [comment]
@ikn Thanks. Can you please add this information in your README.md ?
