### ISSUE TITLE
Patches for curlftpfs-ng

### ISSUE THREAD

**Issue by babam86** [ikn/curlftpfs-ng#2]
Is `curlftpfs-ng` included with all the patches out there, for example here http://slackbuilds.org/slackbuilds/15.0/system/curlftpfs/patches/

I have `curlftpfs` on `Slackware` with all patches but still have issues like:
1. Input/Output error when reading/opening files on the FTP server.
2. Permission denied while reading/opening files on FTP server.
3. Hangs when accessing/browsing the FTP server.

Thanks.

**Comment by ikn** [comment]
No, not all of those patches are included, and there are almost certainly others elsewhere that also aren't included.
